# Generated by Django 4.2.23 on 2025-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='weight_in_grams',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
